name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: npm install -g pnpm

      - run: pnpm install --frozen-lockfile

      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected --target=lint --all --parallel --max-parallel=3
      - run: npx nx affected --target=test --all --parallel --max-parallel=3
      - run: npx nx affected --target=build --all --parallel --max-parallel=3
      - run: npx nx affected --target=e2e-ci --all --parallel --max-parallel=3

      - run: npx nx-cloud stop-ci-run