name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node.js with caching
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install pnpm globally
      - run: npm install -g pnpm

      # Verify pnpm installation (to debug any issues)
      - run: pnpm --version

      # Install dependencies with pnpm
      - run: pnpm install --frozen-lockfile

      # Start Nx Cloud CI run (enables task distribution)
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Set Nx SHAs for caching
      - uses: nrwl/nx-set-shas@v4

      # Run affected commands (lint, test, build, e2e)
      - run: npx nx affected --target=lint --all --parallel --max-parallel=3
      - run: npx nx affected --target=test --all --parallel --max-parallel=3
      - run: npx nx affected --target=build --all --parallel --max-parallel=3
      - run: npx nx affected --target=e2e-ci --all --parallel --max-parallel=3

      # Stop Nx Cloud CI run
      - run: npx nx-cloud stop-ci-run
